In [4]:
import numpy as np
import pandas as pd
import pandas_datareader as web
from sklearn import linear_model
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
symbols = ['HUT','AMD','AAPL','JBL','COIN']
start = '2018-12-01'
end = '2021-12-01'
stocks = web.get_data_yahoo(symbols, start, end)
stocks

Attributes Adj Close                                                  Close  \
Symbols          HUT         AMD        AAPL        JBL        COIN     HUT
Date
2018-12-03     1.400   23.709999   44.854767  24.601515         NaN   1.400
2018-12-04     1.290   21.120001   42.881668  23.831800         NaN   1.290
2018-12-06     1.250   21.299999   42.403549  23.763594         NaN   1.250
2018-12-07     1.267   19.459999   40.891575  22.662624         NaN   1.267
2018-12-10     1.253   19.990000   41.160969  22.516476         NaN   1.253
...              ...         ...         ...        ...         ...     ...
2021-11-24    12.520  157.800003  161.940002  61.959999  312.380005  12.520
2021-11-26    12.190  154.809998  156.809998  59.889999  303.190002  12.190
2021-11-29    12.750  161.910004  160.240005  60.930000  319.390015  12.750
2021-11-30    12.050  158.369995  165.300003  58.459999  315.000000  12.050
2021-12-01    11.780  149.110001  164.770004  58.259998  294.500000  11.780

Attributes                                                 ...    Open  \
Symbols            AMD        AAPL        JBL        COIN  ...     HUT
Date                                                       ...
2018-12-03   23.709999   46.205002  25.250000         NaN  ...   1.389
2018-12-04   21.120001   44.172501  24.459999         NaN  ...   1.290
2018-12-06   21.299999   43.680000  24.389999         NaN  ...   1.290
2018-12-07   19.459999   42.122501  23.260000         NaN  ...   1.267
2018-12-10   19.990000   42.400002  23.110001         NaN  ...   1.253
...                ...         ...        ...         ...  ...     ...
2021-11-24  157.800003  161.940002  61.959999  312.380005  ...  12.120
2021-11-26  154.809998  156.809998  59.889999  303.190002  ...  11.710
2021-11-29  161.910004  160.240005  60.930000  319.390015  ...  12.695
2021-11-30  158.369995  165.300003  58.459999  315.000000  ...  12.850
2021-12-01  149.110001  164.770004  58.259998  294.500000  ...  12.600

Attributes                                                     Volume  \
Symbols            AMD        AAPL        JBL        COIN         HUT
Date
2018-12-03   22.480000   46.115002  25.500000         NaN      1300.0
2018-12-04   23.350000   45.237499  25.100000         NaN       200.0
2018-12-06   20.219999   42.939999  23.980000         NaN     10200.0
2018-12-07   21.299999   43.372501  24.309999         NaN       200.0
2018-12-10   19.350000   41.250000  23.139999         NaN       100.0
...                ...         ...        ...         ...         ...
2021-11-24  149.460007  160.750000  61.340000  309.380005   5053000.0
2021-11-26  155.800003  159.570007  60.080002  301.299988   4730600.0
2021-11-29  157.500000  159.369995  61.000000  312.220001   9032100.0
2021-11-30  163.279999  159.990005  59.990002  320.750000  13282500.0
2021-12-01  160.369995  167.479996  59.970001  318.600006  11006500.0

Attributes
Symbols             AMD         AAPL        JBL       COIN
Date
2018-12-03  139607400.0  163210000.0  2183500.0        NaN
2018-12-04  127392900.0  165377200.0  2059300.0        NaN
2018-12-06  103434700.0  172393600.0  1885500.0        NaN
2018-12-07  105764500.0  169126400.0  1829500.0        NaN
2018-12-10   77984500.0  248104000.0  1996700.0        NaN
...                 ...          ...        ...        ...
2021-11-24   60677100.0   69463600.0   423500.0  2759800.0
2021-11-26   36245100.0   76959800.0   547200.0  2678700.0
2021-11-29   57438900.0   88748200.0   670800.0  4159700.0
2021-11-30   75182500.0  174048100.0  1485500.0  7168400.0
2021-12-01   64039100.0  152052500.0   736700.0  4267500.0

[755 rows x 30 columns]